// Hand-keyed placeholder motions, written as pose functions of the cycle
// phase p ∈ [0,1). Rotations are XYZ Euler offsets from the rest pose; right
// side joints are mirrors of the left (x, -y, -z). Anything generated by
// UniMate with the same name replaces these (see clips/index.js).
const TAU = Math.PI * 2;
const s = (p, o = 0) => Math.sin(TAU * (p + o));
const c = (p, o = 0) => Math.cos(TAU * (p + o));
const pos = (v) => (v > 0 ? v : 0);
const mir = ([x, y, z]) => [x, -y, -z];
/** Smooth bump centred at `at` with half-width `w` (wraps around the loop). */
function bump(p, at, w) {
  let d = Math.abs(p - at);
  d = Math.min(d, 1 - d);
  if (d >= w) return 0;
  const t = 1 - d / w;
  return t * t * (3 - 2 * t);
}

// ------------------------------------------------------------------ bipeds

function legs(rot, p, A, K, lean = 0) {
  for (const [side, o] of [['Left', 0], ['Right', 0.5]]) {
    const sw = s(p, o), cw = c(p, o);
    const knee = K * 0.12 + K * pos(cw);
    const hip = [-A * sw - lean, 0, 0];
    rot[side + 'UpLeg'] = side === 'Left' ? hip : mir(hip);
    rot[side + 'Leg'] = [knee, 0, 0];
    rot[side + 'Foot'] = [-knee * 0.45 + 0.12 * sw, 0, 0];
    rot[side + 'ToeBase'] = [-0.25 * pos(-cw) * pos(sw), 0, 0];
  }
}

function arms(rot, p, { down, swing, bend, raise = 0 }) {
  const sw = s(p);
  rot.LeftArm = [swing * sw - raise, 0, -down];
  rot.RightArm = mir([-swing * sw - raise, 0, -down]);
  rot.LeftForeArm = [0, -bend, 0];
  rot.RightForeArm = mir([0, -bend, 0]);
  rot.LeftHand = [0, 0, -0.15];
  rot.RightHand = mir([0, 0, -0.15]);
}

const human = {
  idle: {
    period: 4,
    pose(p) {
      const rot = {};
      const look = Math.pow(s(p), 3);
      arms(rot, p, { down: 1.33 + 0.03 * s(p, 0.25), swing: 0.03, bend: 0.18 });
      rot.Spine = [0.02, 0, 0];
      rot.Spine1 = [0.02 * s(p * 2), 0, 0];
      rot.Neck = [0, 0.25 * look, 0];
      rot.Head = [0.04 * s(p * 3), 0.25 * look, 0.03 * s(p)];
      rot.LeftUpLeg = [0, 0, 0.04];
      rot.RightUpLeg = mir([0, 0, 0.04]);
      rot.Hips = [0, 0, 0.025 * s(p)];
      return { rot, root: [0.015 * s(p), -0.005 + 0.004 * s(p * 2), 0] };
    },
  },
  walk: {
    period: 1.1, speed: 1.3,
    pose(p) {
      const rot = {};
      legs(rot, p, 0.42, 0.62);
      arms(rot, p, { down: 1.3, swing: 0.34, bend: 0.3 });
      rot.Hips = [0, -0.1 * s(p), 0.03 * c(p)];
      rot.Spine = [0.04, 0, 0];
      rot.Spine1 = [0, 0.18 * s(p), 0];
      rot.Neck = [-0.02, -0.08 * s(p), 0];
      return { rot, root: [-0.02 * c(p), -0.008 - 0.03 * Math.abs(s(p)), 0] };
    },
  },
  run: {
    period: 0.66, speed: 4,
    pose(p) {
      const rot = {};
      legs(rot, p, 0.8, 1.35, -0.05);
      arms(rot, p, { down: 1.22, swing: 0.75, bend: 1.5 });
      rot.Hips = [0, -0.16 * s(p), 0];
      rot.Spine = [0.16, 0, 0];
      rot.Spine1 = [0.06, 0.26 * s(p), 0];
      rot.Neck = [-0.12, -0.12 * s(p), 0];
      return { rot, root: [0, -0.07 + 0.055 * Math.abs(s(p)), 0] };
    },
  },
  panic: {
    // two strides per loop so the head can look back once
    period: 1.26, speed: 4.6,
    pose(p) {
      const rot = {};
      const q = (p * 2) % 1;
      legs(rot, q, 0.78, 1.3, -0.05);
      rot.LeftArm = [-0.5 + 0.35 * s(q, 0.1), 0, 0.55 + 0.4 * s(q, 0.3)];
      rot.RightArm = mir([-0.5 - 0.35 * s(q, 0.1), 0, 0.55 + 0.4 * s(q, 0.8)]);
      rot.LeftForeArm = [0, -0.8 - 0.4 * s(q), 0];
      rot.RightForeArm = mir([0, -0.8 + 0.4 * s(q), 0]);
      rot.Hips = [0, -0.14 * s(q), 0];
      rot.Spine = [0.24, 0, 0];
      rot.Spine1 = [0.05, 0.2 * s(q), 0];
      const back = bump(p, 0.5, 0.3);
      rot.Neck = [-0.1, 0.7 * back, 0];
      rot.Head = [-0.1 * back, 0.6 * back, 0];
      return { rot, root: [0, -0.07 + 0.06 * Math.abs(s(q)), 0] };
    },
  },
};

const firefighter = {
  ...human,
  aim: {
    period: 0.8,
    pose(p) {
      const rot = {};
      rot.LeftUpLeg = [-0.32, 0, 0.06];
      rot.LeftLeg = [0.38, 0, 0];
      rot.LeftFoot = [-0.06, 0, 0];
      rot.RightUpLeg = mir([0.28, 0, 0.04]);
      rot.RightLeg = [0.2, 0, 0];
      rot.RightFoot = [-0.1, 0, 0];
      rot.Spine = [0.12, 0, 0];
      rot.Spine1 = [0.04, 0.24, 0];
      // right hand (extinguisher) forward, bracing hand under it
      rot.RightArm = [0.02 * s(p * 2), 1.45 + 0.05 * s(p), 0.12 + 0.03 * s(p * 2)];
      rot.RightForeArm = [0, 0.1, 0];
      rot.LeftArm = [0.1, -1.2, -0.35];
      rot.LeftForeArm = [0, -1.0, 0];
      rot.Neck = [0.06, -0.14, 0];
      rot.Head = [0.08, -0.1, 0];
      return { rot, root: [0.01 * s(p), -0.06 + 0.006 * s(p * 2), -0.02 * s(p * 2)] };
    },
  },
};

// ------------------------------------------------------------------ small quadrupeds

function smallHop(H, amp) {
  return (p) => {
    const rot = {};
    const air = p < 0.5 ? Math.sin(Math.PI * (p / 0.5)) : 0;
    rot.Hips = [-0.22 * c(p) + 0.1 * s(p), 0, 0];
    rot.Spine = [-0.15 * amp * s(p), 0, 0];
    rot.Spine1 = [-0.1 * amp * s(p), 0, 0];
    rot.Neck = [0.12 * c(p), 0, 0];
    rot.Head = [0.1 * c(p), 0, 0];
    for (const [L, m] of [['L_', (v) => v], ['R_', mir]]) {
      rot[L + 'Thigh'] = m([0.62 * amp * c(p), 0, 0]);
      rot[L + 'Shin'] = m([-0.45 * amp * c(p), 0, 0]);
      rot[L + 'Foot'] = m([0.35 * amp * c(p), 0, 0]);
      rot[L + 'Upperarm'] = m([-0.5 * amp * s(p, 0.04), 0, 0]);
      rot[L + 'Forearm'] = m([0.5 * pos(s(p, 0.5)), 0, 0]);
      rot[L + 'Ear'] = m([-0.35 * air - 0.1, 0, -0.14]);
      rot[L + 'Ear1'] = m([-0.3 * air, 0, 0]);
    }
    rot.Tail = [0.35 * s(p), 0, 0];
    rot.Tail1 = [0.25 + 0.2 * s(p, -0.1), 0, 0];
    rot.Tail2 = [0.35 + 0.25 * s(p, -0.2), 0, 0];
    return { rot, root: [0, H * air, 0] };
  };
}

const small = {
  idle: {
    period: 3.2,
    pose(p) {
      const rot = {};
      const sniff = bump(p, 0.25, 0.14);
      const look = Math.pow(s(p, 0.1), 3);
      rot.Hips = [0.03, 0, 0];
      rot.Spine1 = [0.03 * s(p * 2), 0, 0];
      rot.Neck = [-0.08, 0.45 * look, 0];
      rot.Head = [0.07 * sniff * Math.sin(TAU * p * 18), 0.15 * look, 0];
      const twitch = bump(p, 0.68, 0.05);
      for (const [L, m] of [['L_', (v) => v], ['R_', mir]]) {
        rot[L + 'Ear'] = m([0.05, 0, -0.14 - (L === 'L_' ? 0.35 * twitch : 0)]);
        rot[L + 'Thigh'] = m([-0.1, 0, 0]);
        rot[L + 'Shin'] = m([0.1, 0, 0]);
      }
      rot.Tail = [0.1 * Math.sin(TAU * p * 8) * bump(p, 0.85, 0.08), 0, 0];
      rot.Tail1 = [0.3 + 0.08 * s(p), 0, 0];
      rot.Tail2 = [0.45 + 0.1 * s(p, -0.1), 0, 0];
      return { rot, root: [0, 0.003 * s(p * 2), 0] };
    },
  },
  hop: { period: 0.46, speed: 1.6, pose: smallHop(0.06, 1) },
  run: { period: 0.3, speed: 4.5, pose: smallHop(0.1, 1.3) },
};

// ------------------------------------------------------------------ deer

function deerLegs(rot, p, phases, A, K) {
  for (const [L, m] of [['L_', (v) => v], ['R_', mir]]) {
    const h = phases[L + 'hind'], f = phases[L + 'front'];
    rot[L + 'Thigh'] = m([-A * s(p, h), 0, 0]);
    rot[L + 'Shin'] = m([0.1 + 0.55 * K * pos(c(p, h)), 0, 0]);
    rot[L + 'Foot'] = m([-0.05 - 0.4 * K * pos(c(p, h)), 0, 0]);
    rot[L + 'Upperarm'] = m([-A * 1.05 * s(p, f), 0, 0]);
    rot[L + 'Forearm'] = m([1.0 * K * pos(c(p, f)), 0, 0]);
    rot[L + 'Hand'] = m([0.35 * K * pos(c(p, f)), 0, 0]);
  }
}

const deer = {
  idle: {
    // graze, chew, then lift the head and look around
    period: 5.5,
    pose(p) {
      const rot = {};
      const t = p < 0.08 ? p / 0.08 : p < 0.6 ? 1 : p < 0.7 ? 1 - (p - 0.6) / 0.1 : 0;
      const g = t * t * (3 - 2 * t);
      const look = (1 - g) * Math.sin(TAU * (p - 0.7) / 0.3);
      rot.Spine1 = [0.28 * g, 0, 0];
      rot.Neck = [1.75 * g, 0.45 * look, 0];
      rot.Head = [0.55 * g + 0.05 * g * Math.sin(TAU * p * 11), 0.2 * look, 0];
      for (const [L, m] of [['L_', (v) => v], ['R_', mir]]) {
        rot[L + 'Upperarm'] = m([-0.12 * g, 0, -0.06 * g]);
        rot[L + 'Forearm'] = m([0.06 * g, 0, 0]);
        rot[L + 'Ear'] = m([0, 0.3 * bump(p, L === 'L_' ? 0.3 : 0.82, 0.04), 0]);
      }
      rot.Tail = [0.15 * Math.sin(TAU * p * 9) * bump(p, 0.45, 0.06), 0, 0];
      return { rot, root: [0, -0.06 * g, 0] };
    },
  },
  walk: {
    period: 1.25, speed: 1.5,
    pose(p) {
      const rot = {};
      deerLegs(rot, p, { L_hind: 0, L_front: 0.25, R_hind: 0.5, R_front: 0.75 }, 0.32, 1);
      rot.Hips = [0, 0.04 * s(p), 0];
      rot.Neck = [0.05 * s(p * 2), 0, 0];
      rot.Head = [-0.04 * s(p * 2), 0, 0];
      rot.Tail = [0.05 * s(p), 0, 0];
      return { rot, root: [0, -0.012 * Math.abs(s(p * 2)), 0] };
    },
  },
  gallop: {
    period: 0.5, speed: 7,
    pose(p) {
      const rot = {};
      deerLegs(rot, p, { L_hind: 0, R_hind: 0.08, L_front: 0.5, R_front: 0.58 }, 0.72, 1.4);
      rot.Hips = [0.12 * s(p, 0.1), 0, 0];
      rot.Spine = [0.08 * s(p, 0.35), 0, 0];
      rot.Spine1 = [0.08 * s(p, 0.35), 0, 0];
      rot.Neck = [-0.35 + 0.14 * s(p, 0.2), 0, 0];
      rot.Head = [0.2 - 0.1 * s(p, 0.2), 0, 0];
      rot.L_Ear = [-0.6, 0, 0];
      rot.R_Ear = [-0.6, 0, 0];
      rot.Tail = [0.9, 0, 0];
      return { rot, root: [0, 0.03 + 0.07 * pos(s(p, 0.3)), 0] };
    },
  },
};

// ------------------------------------------------------------------ bird

function foldWings(rot) {
  rot.L_Wing = [0, 1.45, -0.25];
  rot.L_Wing1 = [0, -2.7, 0];
  rot.L_Wing2 = [0, 2.7, 0];
  rot.R_Wing = mir(rot.L_Wing);
  rot.R_Wing1 = mir(rot.L_Wing1);
  rot.R_Wing2 = mir(rot.L_Wing2);
}

const bird = {
  idle: {
    period: 1.8,
    pose(p) {
      const rot = {};
      foldWings(rot);
      const peck = bump(p, 0.3, 0.07) + bump(p, 0.52, 0.07);
      const look = bump(p, 0.8, 0.12);
      rot.Hips = [0.35 * peck, 0, 0];
      rot.Neck = [0.8 * peck, 0.6 * look, 0];
      rot.Head = [0.4 * peck, 0.4 * look, 0];
      rot.Tail = [-0.3 * peck, 0, 0];
      return { rot, root: [0, 0.012 * bump(p, 0.9, 0.06), 0] };
    },
  },
  fly: {
    period: 0.26, speed: 6,
    pose(p) {
      const rot = {};
      const f = s(p);
      rot.L_Wing = [0, 0.15 * s(p, 0.25), 0.95 * f];
      rot.L_Wing1 = [0, 0.1 * s(p, 0.2), 0.45 * s(p, -0.08)];
      rot.L_Wing2 = [0, 0, 0.4 * s(p, -0.16)];
      for (const k of ['Wing', 'Wing1', 'Wing2']) rot['R_' + k] = mir(rot['L_' + k]);
      rot.L_Thigh = [1.2, 0, 0];
      rot.R_Thigh = [1.2, 0, 0];
      rot.Hips = [-0.1, 0, 0];
      rot.Tail = [0.1 * s(p, 0.3), 0, 0];
      return { rot, root: [0, -0.012 * f, 0] };
    },
  },
};

export const PROCEDURAL = { human, firefighter, rabbit: small, squirrel: small, deer, bird };
